-- MySQL Script generated by MySQL Workbench
-- Mon Aug 15 00:59:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vivebio_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vivebio_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vivebio_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `vivebio_db` ;

-- -----------------------------------------------------
-- Table `vivebio_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivebio_db`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `image` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `vivebio_db`.`properties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivebio_db`.`properties` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `vivebio_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivebio_db`.`products` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `category_Id` INT UNSIGNED NOT NULL,
  `volume` INT UNSIGNED NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  `discount` INT UNSIGNED NOT NULL,
  `property_id` INT UNSIGNED NOT NULL,
  `stock` INT UNSIGNED NOT NULL,
  `ingredients` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_products_categories_idx` (`category_Id` ASC) VISIBLE,
  INDEX `FK_products_properties_idx` (`property_id` ASC) VISIBLE,
  CONSTRAINT `FK_products_categories`
    FOREIGN KEY (`category_Id`)
    REFERENCES `vivebio_db`.`categories` (`id`),
  CONSTRAINT `FK_products_properties`
    FOREIGN KEY (`property_id`)
    REFERENCES `vivebio_db`.`properties` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 104
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `vivebio_db`.`rols`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivebio_db`.`rols` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `vivebio_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivebio_db`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `rol_id` INT UNSIGNED NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_users_rols_idx` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `FK_users_rols`
    FOREIGN KEY (`rol_id`)
    REFERENCES `vivebio_db`.`rols` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 42
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `vivebio_db`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivebio_db`.`carts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `cant` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_carts_users_idx` (`user_id` ASC) VISIBLE,
  INDEX `FK_products_users_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FK_carts_products`
    FOREIGN KEY (`product_id`)
    REFERENCES `vivebio_db`.`products` (`id`),
  CONSTRAINT `FK_carts_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `vivebio_db`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `vivebio_db`.`favourites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivebio_db`.`favourites` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_users_favourites_idx` (`user_id` ASC) VISIBLE,
  INDEX `FK_products_favourites_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FK_products_favourites`
    FOREIGN KEY (`product_id`)
    REFERENCES `vivebio_db`.`products` (`id`),
  CONSTRAINT `FK_users_favourites`
    FOREIGN KEY (`user_id`)
    REFERENCES `vivebio_db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `vivebio_db`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivebio_db`.`payments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `vivebio_db`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivebio_db`.`status` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `vivebio_db`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivebio_db`.`orders` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `status_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `payment_id` INT UNSIGNED NOT NULL,
  `total` DECIMAL(6,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_orders_status_idx` (`status_id` ASC) VISIBLE,
  INDEX `FK_orders_users_idx` (`user_id` ASC) VISIBLE,
  INDEX `FK_orders_payment_idx` (`payment_id` ASC) VISIBLE,
  CONSTRAINT `FK_orders_payments`
    FOREIGN KEY (`payment_id`)
    REFERENCES `vivebio_db`.`payments` (`id`),
  CONSTRAINT `FK_orders_status`
    FOREIGN KEY (`status_id`)
    REFERENCES `vivebio_db`.`status` (`id`),
  CONSTRAINT `FK_orders_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `vivebio_db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `vivebio_db`.`productsimages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivebio_db`.`productsimages` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `primary` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_products_prodects_images_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FK_products_prodects_images`
    FOREIGN KEY (`product_id`)
    REFERENCES `vivebio_db`.`products` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 72
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
